### ISSUE TITLE
Cannot connect to binaryai server 

### ISSUE THREAD

**Issue by shiraishi-mai** [binaryai/sdk#110]
Hi all, I cannot connect to binaryai ida api and also the https://binaryai.tencent.com/apply-token since last week, is there any maintenance ?

**Comment by nforest** [comment]
> Hi all, I cannot connect to binaryai ida api and also the https://binaryai.tencent.com/apply-token since last week, is there any maintenance ?

Hi, we didn't find any errors in our backend service.
Could you please try again? And please attach the error logs here if you cannot connect to the backend.

**Comment by shiraishi-mai** [comment]
> > Hi all, I cannot connect to binaryai ida api and also the https://binaryai.tencent.com/apply-token since last week, is there any maintenance ?
> 
> Hi, we didn't find any errors in our backend service.
> Could you please try again? And please attach the error logs here if you cannot connect to the backend.


Hi, thx for your prompt reply. The error message earlier this week (this morning) is related to timeout of the request module (But I can't reproduce at the moment)

The current error message pop out is "Wrong token"
But I can't apply for a new token now (I cannot reach the https://binaryai.tencent.com/apply-token from all of the devices in different network)

And may I confirm the api is here ? 
https://github.com/binaryai/sdk/blob/master/binaryai/ida_binaryai.py#L95

**Comment by davendu** [comment]
Hi @shiraishi-mai 

> The error message earlier this week (this morning) is related to timeout of the request module (But I can't reproduce at the moment). 

All our servers (token apply and API endpoint) are deployed in the mainland China at this time, so there might have some connectivity issues for worldwide users. From our metric system we can see some request failed due to poor network connection. This have been on our list but currently we don't have a schedule for this. 

> The current error message pop out is "Wrong token". But I can't apply for a new token now (I cannot reach the https://binaryai.tencent.com/apply-token from all of the devices in different network

This is something strange. If you would like to provide some information, you can send your token to my mail (see my profile for the address). Also it would be better if you can specify the IP address, carrier, and/or the country you are accessing from, so we can see if our ISP have any idea about optimizing it. (It's okay to mask the last 16bit of your IP address if you want. For example, 192.168.0.0/16). But since the international connection is too complex...it might be harder than just place some servers abroad. Not sure which is the best way yet.

> And may I confirm the api is here ?
> https://github.com/binaryai/sdk/blob/master/binaryai/ida_binaryai.py#L95

Yes, the endpoint is `https://api.binaryai.tencent.com/v1/endpoint`. It is an GraphQL endpoint, with introspection enabled. If you want to use it manually, make sure you are carrying your token in the header: `Token: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`

**Comment by davendu** [comment]
Problem already solved.

Quick summary:

1. Token verify was okay. It was a wrong input from user (seems some strange characters appended after token).

2. The site was not accessible due to a wrong config in our Nginx server. It has now been resolved by deploying some instances in Hong Kong DC. It would also be helpful for other oversea users to speed up accessing our services.
